"""Repository Protocol群。docs/api/repositories.md の型シグネチャに対応する。

UnitOfWorkは本タスク（Phase2 Task1）の対象外。LearningRepositoryはADR-0044が
前提とするJobRunnerの依存契約を整備するため、Phase3 Task10-0.2で追加した
（具象実装は対象外、docs/api/repositories.md#learningrepository）。
"""

from datetime import date, datetime
from typing import Protocol

from mod_personnel_db.models import (
    CandidateId,
    CandidateRecord,
    ExportId,
    ExportRecord,
    GoldRecord,
    GoldRecordId,
    Job,
    JobId,
    KnowledgeItem,
    Layout,
    LearningRecord,
    LearningRecordId,
    LearningStatus,
    NormalizedRecord,
    ParserVersion,
    ParserVersionId,
    PdfId,
    PdfRecord,
    PersonnelSection,
    PersonnelSectionId,
    RawRecord,
    ReviewItem,
    ReviewItemId,
    ReviewSessionId,
    ValidationResult,
)


class CandidateRepository(Protocol):
    def add_section(self, section: PersonnelSection) -> PersonnelSectionId: ...
    def get_section(self, section_id: PersonnelSectionId) -> PersonnelSection | None: ...

    def add_raw(self, section_id: PersonnelSectionId, record: RawRecord) -> CandidateId: ...
    def attach_normalized(
        self, candidate_id: CandidateId, normalized: NormalizedRecord
    ) -> None: ...
    def update_validation(self, candidate_id: CandidateId, result: ValidationResult) -> None: ...

    def get(self, candidate_id: CandidateId) -> CandidateRecord | None: ...
    def list_by_section(self, section_id: PersonnelSectionId) -> tuple[CandidateRecord, ...]: ...
    def list_pending_validation(self) -> tuple[CandidateRecord, ...]: ...
    def list_failed_validation(self) -> tuple[CandidateRecord, ...]: ...


class GoldRepository(Protocol):
    def add_version(
        self,
        candidate_id: CandidateId,
        record: NormalizedRecord,
        person_key: str,
        effective_date: date,
        appointment_type: str,
    ) -> GoldRecordId: ...

    def supersede(self, old_id: GoldRecordId, new_id: GoldRecordId) -> None: ...

    def get_current(self, person_key: str, effective_date: date) -> GoldRecord | None: ...
    def get_history(self, person_key: str) -> tuple[GoldRecord, ...]: ...
    def list_current(self, as_of: datetime | None = None) -> tuple[GoldRecord, ...]: ...


class KnowledgeRepository(Protocol):
    def upsert_item(self, item: KnowledgeItem) -> None: ...

    def get_item(
        self, category: str, item_key: str, as_of: date | None = None
    ) -> KnowledgeItem | None: ...
    def list_items(self, category: str) -> tuple[KnowledgeItem, ...]: ...

    def get_layout(self, era_id: str, version: int | None = None) -> Layout | None: ...
    def list_active_layouts(self, as_of: date | None = None) -> tuple[Layout, ...]: ...


class LearningRepository(Protocol):
    def add(self, record: LearningRecord) -> LearningRecordId: ...

    def update(self, record_id: LearningRecordId, **fields: object) -> LearningRecord:
        """ライフサイクル遷移に伴うフィールド更新（docs/architecture/learning_dataset.md参照）。"""
        ...

    def get(self, record_id: LearningRecordId) -> LearningRecord | None: ...
    def list_by_status(self, status: LearningStatus) -> tuple[LearningRecord, ...]: ...
    def list_by_error_category(self, category: str) -> tuple[LearningRecord, ...]: ...
    def list_by_parser_version(
        self, parser_version_id: ParserVersionId
    ) -> tuple[LearningRecord, ...]: ...


class PDFRepository(Protocol):
    def add(self, pdf: PdfRecord) -> PdfId: ...
    def get(self, pdf_id: PdfId) -> PdfRecord | None: ...
    def get_by_hash(self, content_hash: str) -> PdfRecord | None: ...
    def update_status(self, pdf_id: PdfId, status: str) -> None: ...
    def list_by_status(self, status: str) -> tuple[PdfRecord, ...]: ...


class JobRepository(Protocol):
    def add(self, job: Job) -> JobId: ...
    def update_status(
        self, job_id: JobId, status: str, processed_count: int, failed_count: int
    ) -> None: ...
    def get(self, job_id: JobId) -> Job | None: ...
    def list_running(self) -> tuple[Job, ...]: ...

    def record_parser_version(self, version: ParserVersion) -> ParserVersionId: ...
    def get_parser_version(self, code_version: str) -> ParserVersion | None: ...
    def get_latest_parser_version(self) -> ParserVersion | None: ...


class ExportRepository(Protocol):
    def add(self, export: ExportRecord) -> ExportId: ...
    def get(self, export_id: ExportId) -> ExportRecord | None: ...
    def list_recent(self, limit: int = 10) -> tuple[ExportRecord, ...]: ...
    def get_latest(self, format: str) -> ExportRecord | None: ...


class ReviewRepository(Protocol):
    def create_session(self, reviewer: str, reason: str) -> ReviewSessionId: ...
    def close_session(self, session_id: ReviewSessionId, status: str) -> None: ...
    def add_change(self, session_id: ReviewSessionId, item: ReviewItem) -> ReviewItemId: ...
    def list_changes(self, session_id: ReviewSessionId) -> tuple[ReviewItem, ...]: ...
    def list_open_sessions(self) -> tuple[ReviewSessionId, ...]: ...
