"""ドメインモデル公開窓口。docs/api/models.md の平坦な名前空間に対応する（13モデル全種）。"""

from mod_personnel_db.models.candidate import (
    CandidateRecord,
    NormalizedRecord,
    NormalizedValue,
    PersonnelSection,
    RawRecord,
)
from mod_personnel_db.models.document import (
    Document,
    DocumentAnalysisResult,
    DocumentMetadata,
    DocumentStatistics,
    DocumentV1,
    DocumentWarning,
    PageV1,
)
from mod_personnel_db.models.enums import (
    ConfidenceBand,
    ErrorCategory,
    LearningStatus,
    PipelineStageName,
    RegressionStatus,
)
from mod_personnel_db.models.export import (
    ExportArtifact,
    ExportFormat,
    ExportRecord,
    PersonnelRecord,
    Provenance,
    SourcePdf,
)
from mod_personnel_db.models.extraction import (
    ExtractionCandidate,
    ExtractionEvidence,
    FieldExtractionResult,
    RawField,
)
from mod_personnel_db.models.feature import FeatureVector
from mod_personnel_db.models.gold import GoldRecord
from mod_personnel_db.models.ids import (
    CandidateId,
    DocumentId,
    ExportId,
    GoldRecordId,
    JobId,
    KnowledgeItemId,
    LayoutId,
    LearningRecordId,
    ParserVersionId,
    PdfId,
    PersonnelSectionId,
    ReviewItemId,
    ReviewSessionId,
)
from mod_personnel_db.models.job import Job, ParserVersion
from mod_personnel_db.models.knowledge import (
    KnowledgeItem,
    KnowledgeSnapshot,
    Layout,
    ValidationRuleSet,
)
from mod_personnel_db.models.layout_detection import (
    BoundingBoxStatistics,
    LayoutArtifact,
    LayoutArtifactPage,
    LayoutCandidate,
    LayoutConfidence,
    LayoutDefinition,
    LayoutDetectionResult,
    LayoutEvidence,
    LayoutMatch,
    LayoutRule,
    LayoutRuleKind,
    LayoutWarning,
    PageStatistics,
    RotationStatistics,
)
from mod_personnel_db.models.learning import LearningRecord
from mod_personnel_db.models.normalization import (
    NormalizationCandidate,
    NormalizationEvidence,
    NormalizationResult,
    NormalizedField,
)
from mod_personnel_db.models.pdf import PdfRecord
from mod_personnel_db.models.review import ReviewItem
from mod_personnel_db.models.sections import SectionCandidate, SectionEvidence, SectionParseResult
from mod_personnel_db.models.validation import (
    ValidationCandidate,
    ValidationError,
    ValidationEvidence,
    ValidationResult,
    ValidationWarning,
)
from mod_personnel_db.models.values import Confidence

__all__ = [
    "BoundingBoxStatistics",
    "CandidateId",
    "CandidateRecord",
    "Confidence",
    "ConfidenceBand",
    "Document",
    "DocumentAnalysisResult",
    "DocumentId",
    "DocumentMetadata",
    "DocumentStatistics",
    "DocumentV1",
    "DocumentWarning",
    "ErrorCategory",
    "ExportArtifact",
    "ExportFormat",
    "ExportId",
    "ExportRecord",
    "ExtractionCandidate",
    "ExtractionEvidence",
    "FeatureVector",
    "FieldExtractionResult",
    "GoldRecord",
    "GoldRecordId",
    "Job",
    "JobId",
    "KnowledgeItem",
    "KnowledgeItemId",
    "KnowledgeSnapshot",
    "Layout",
    "LayoutArtifact",
    "LayoutArtifactPage",
    "LayoutCandidate",
    "LayoutConfidence",
    "LayoutDefinition",
    "LayoutDetectionResult",
    "LayoutEvidence",
    "LayoutId",
    "LayoutMatch",
    "LayoutRule",
    "LayoutRuleKind",
    "LayoutWarning",
    "LearningRecord",
    "LearningRecordId",
    "LearningStatus",
    "NormalizationCandidate",
    "NormalizationEvidence",
    "NormalizationResult",
    "NormalizedField",
    "NormalizedRecord",
    "NormalizedValue",
    "PageStatistics",
    "PageV1",
    "ParserVersion",
    "ParserVersionId",
    "PdfId",
    "PdfRecord",
    "PersonnelRecord",
    "PersonnelSection",
    "PersonnelSectionId",
    "PipelineStageName",
    "Provenance",
    "RawField",
    "RawRecord",
    "RegressionStatus",
    "ReviewItem",
    "ReviewItemId",
    "ReviewSessionId",
    "RotationStatistics",
    "SectionCandidate",
    "SectionEvidence",
    "SectionParseResult",
    "SourcePdf",
    "ValidationCandidate",
    "ValidationError",
    "ValidationEvidence",
    "ValidationResult",
    "ValidationRuleSet",
    "ValidationWarning",
]
